import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import VueScrollTo from 'vue-scrollto'
import { OhVueIcon, addIcons } from "oh-vue-icons";
import { CoHtml5Shield, 
    CoCss3Shiled, 
    SiJavascript, 
    CoVueJs, 
    CoReact, 
    SiTailwindcss, 
    FaBootstrap, 
    SiVite, 
    CoJest, 
    CoGo, 
    CoRust, 
    SiCsharp,
    SiPython,
    CoMysql,
    CoPostgresql,
    SiMongodb,
    SiAmazondynamodb,
    SiDocker,
    SiKubernetes,
    SiNginx,
    SiFastapi,
    SiExpress,
    CoUnity,
    CoUnrealEngine,
    SiCplusplus,
    CoBlender,
    SiAdobephotoshop,
    SiAudacity,
    CoGit,
    SiGithub,
    SiGitlab,
    CoAmazonAws,
    SiMicrosoftazure,
    BiSun,
    BiMoonStars} from "oh-vue-icons/icons";

addIcons(CoHtml5Shield, 
    CoCss3Shiled, 
    SiJavascript, 
    CoVueJs, 
    CoReact, 
    SiTailwindcss, 
    FaBootstrap, 
    SiVite, 
    CoJest, 
    CoGo, 
    CoRust, 
    SiCsharp,
    SiPython,
    CoMysql,
    CoPostgresql,
    SiMongodb,
    SiAmazondynamodb,
    SiDocker,
    SiKubernetes,
    SiNginx,
    SiFastapi,
    SiExpress,
    CoUnity,
    CoUnrealEngine,
    SiCplusplus,
    CoBlender,
    SiAdobephotoshop,
    SiAudacity,
    CoGit,
    SiGithub,
    SiGitlab,
    CoAmazonAws,
    SiMicrosoftazure,
    BiSun,
    BiMoonStars);

const app = createApp(App);
app.use(VueScrollTo);
app.component("v-icon", OhVueIcon);
app.mount('#app');

